name: Deploy

# Trigger the workflow on push and
# pull request events on the production branch
on:
    push:
        branches:
            - giveawaysfinance
# Authenticate to the the server via ssh
# and run our deployment script
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Deploy to server
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  port: ${{ secrets.PORT }}
                  key: ${{ secrets.SSHKEY }}
                  script: |
                      rm -rf /var/www/build
                      cd /var/www && git clone git@github.com:giveawaysfinance/giveaways.git build
                      cp /var/www/envs/.sleep /var/www/build/.env
                      cd /var/www/build && ./.scripts/deploy.sh
                      rm -rf /var/www/giveawaysfinance_io_back
                      mv /var/www/giveaways.finance /var/www/giveawaysfinance_io_back
                      mv /var/www/build /var/www/giveaways.finance
                      cd /var/www/giveaways.finance && php artisan optimize
                      cd /var/www/giveaways.finance && php artisan storage:link
                      cd /var/www/giveaways.finance && sudo chgrp -R www-data storage bootstrap/cache
                      cd /var/www/giveaways.finance && sudo chmod -R ug+rwx storage bootstrap/cache
